spring.application.name=project-manager

# ? FIXED DATABASE CONFIG
spring.datasource.url=${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? IMPORTANT (dialect fix)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true