spring.application.name=project-manager


spring.datasource.url=jdbc:mysql://localhost:3306/projectdb
spring.datasource.username=root
spring.datasource.password=Kunal@0728

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
